version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - canonicalheader
    - depguard
    - err113
    - exhaustruct
    - ineffassign
    - ireturn
    - mnd
    - staticcheck
    - tagliatelle
    - unparam
    - varnamelen
    - wrapcheck
    - funcorder
    - gochecknoglobals
    - dupl
  settings:
    funlen:
      lines: -1
      statements: -1
    revive:
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
